Makefile
docs/api-documents.md
go.mod
tool/api-docs-gen/cmd/docgen.go
tool/api-docs-gen/docgen.go

command:
```shell
make api-docs-gen 
```
auto genrerate api document to ./docs/api-document.md

auto generate api documents

---

.gitignore
docs/api-documents.md
tool/api-docs-gen/docgen.go

api document generation provide new added types

fix: provide new types example value

---

.github/workflows/tag-workflow.yml
app/venus-sealer/proving.go
go.mod
go.sum

support mocking window post faulty sectors

feat: support mocking wdpost faulty sectors

---

api/api_types.go
api/impl/strageminer.go
api/storage_struct.go
app/venus-sealer/sectors.go
gen/main.go
models/sqlite/sector_info.go
sector-storage/ffiwrapper/basicfs/fs.go
sector-storage/ffiwrapper/sealer_cgo.go
sector-storage/manager.go
sector-storage/storiface/filetype.go
sector-storage/storiface/resources.go
storage-sealing/checks.go
storage-sealing/fsm.go
storage-sealing/garbage.go
storage-sealing/input.go
storage-sealing/states_failed.go
storage-sealing/states_replica_update.go
storage-sealing/states_sealing.go
storage/miner_sealing.go
types/cbor_gen.go

sector status output snapdeal related information.

feat: snapdeal: sector status output snapdeal related info

---

api/impl/strageminer.go
api/storage_struct.go
app/venus-sealer/sectors.go
gen/main.go
models/sqlite/sector_info.go
sector-storage/ffiwrapper/basicfs/fs.go
sector-storage/ffiwrapper/sealer_cgo.go
sector-storage/manager.go
sector-storage/storiface/filetype.go
sector-storage/storiface/resources.go
storage-sealing/checks.go
storage-sealing/fsm.go
storage-sealing/garbage.go
storage-sealing/input.go
storage-sealing/states_failed.go
storage-sealing/states_replica_update.go
storage-sealing/states_sealing.go
storage/miner_sealing.go
types/cbor_gen.go

fix: snapdeal: ReplicaUpdateFailed

---

storage-sealing/states_replica_update.go

feat: snap-deal: upgrade ffi

---

config/default_config.go
constants/proof-params/parameters.json

feat: consensus: update proof parameter & ffi

---

app/venus-sealer/main.go
app/venus-sealer/params.go

feat: cli: fetch params

---

app/venus-sealer/init.go
builder.go
go.mod
go.sum
modules.go

supporting read piece data from s3 preSignedUrl

feat: data transfer: support s3 PreSignedUrl

---

modules.go

fix: fetch param: pen slip

---

constants/version.go

fix: build version

---

config/load.go
config/load_test.go

MarketNode configuration in v1.4.0 compatible with v1

feat: configuration: compatible 

---

storage-sealing/fsm.go

next state of FinalizeReplicaUpdate should be UpdateActivating

fix: snap-deal: incorrect state transfer 

---

.gitignore
tool/convert-with-lotus/from-lotus/main.go
tool/convert-with-lotus/modules/modules.go
tool/convert-with-lotus/to-lotus/main.go
tool/convert-with-lotus/types/README.md
tool/convert-with-lotus/types/cbor_gen.go
tool/convert-with-lotus/types/cbor_gen/main.go
tool/convert-with-lotus/types/convert.go
tool/convert-with-lotus/types/sector_state.go
tool/convert-with-lotus/types/types.go

feat: op tool: upgrade sector convert tool

---

api/impl/strageminer.go
api/market-client.go
api/messager-client.go
api/storage_struct.go
builder.go
go.mod
go.sum
market_client/market_client.go
market_client/market_event.go
market_client/modules.go
modules.go
proof_client/modules.go
proof_client/proof_client.go
proof_client/proof_event.go
storage-sealing/deals.go
storage-sealing/sealing.go
storage/adapter_storage_miner.go
storage/miner.go

refactor: create gateway client

---

.github/workflows/tag-workflow.yml
app/panic-reporter/panic_reporter.go

fix: github action: auto release prefix sensitive

---

market_client/modules.go
proof_client/modules.go

fix: configs: compatible for market event configurations

---

builder.go
modules.go

feat: post warmup

---

Makefile
dockerfile

change to build docker image from local repo rather than from git chech out
pass env var BUILD_DOCKER_PROXY to docker when make image

fix: venus-sealer: change to  build docker image from local repo 

---

dockerfile

fix https://github.com/filecoin-project/venus/issues/4999
update dependencies of ddl from base docker image

fix #4999 : venus-sealer : update dependencies of ddl
